import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import { Button, Icon, Gnb } from '@components/index';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Gnb></Gnb>
      <main>
        <Button size="large">Generate</Button>
        <Button size="large" loading>
          Loading...
        </Button>
        <Button>Connect Wallet</Button>
        <Button size="small">Show Edit</Button>
        <Button size="small">Hide Edit</Button>
        <Icon name="copy" fill="red" size={56}></Icon>
        <Icon name="chevron_down" fill="red" size={56}></Icon>
        <Icon name="chevron_up" fill="red" size={56}></Icon>
      </main>
    </>
  );
}
